# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/web-app-react/

    steps:
      - checkout
      - restore_cache: # special step to restore the dependency cache
          key: dependency-cache-{{ checksum "./web-app-react/package.json" }}

      - run: cd web-app-react && yarn install

      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "./web-app-react/package.json" }}
          paths:
            - ./node_modules


      # run Linting!
      - run: cd web-app-react && yarn lint

      # run tests!
      - run: cd web-app-react && yarn test