export default {
    LOAD_DATA_START:`LOAD_DATA_START`,
    LOAD_DATA_ERROR:`LOAD_DATA_ERROR`,
    LOAD_DATA_SUCCESS:`LOAD_DATA_SUCCESS`,
    ON_CONNECT:`ON_CONNECT`,
    ON_DISCONNECT:`ON_CONNECT`
};

